# Generated by Django 4.2.16 on 2024-11-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtransaction',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
